## JVM Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.235
neo_version_range=[21.1,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_id=thaumaturgicintegrations
mod_name=Thaumaturgic-Integrations
mod_license=All Rights Reserved (see LICENSE)
mod_version=0.1.0
mod_group_id=com.reclipse
mod_authors=Reclipse, Saereth
mod_description=Integrations between Thaumaturge and other magic mods.

## Dependencies
jei_version=19.36.0.360
curios_version=9.5.1
jade_version=15.10.5+neoforge

# 2.0.0 alpha
astral_sorcery_file=8963622
observerlib_file=8726128

# botania_version=457-20260922.100929-7 (it's currently a dev snapshot, can't really dev on it)

occultism_version=1.21.1-neoforge-1.224.4
neovitae_version=1.21.1-1.1.28
ars_nouveau_version=5.12.0.1368
irons_spells_version=1.21.1-3.16.3
malum_version=1.21.1-1.8.2.150

thaumaturge_version=0.4.6

# Modrinth Sources
geckolib_version_id=Grwn5rUB
modonomicon_version=1.21.1-1.120.7
smartbrainlib_version_id=O5EpeqI3

## Publish Properties
curseforge_id=
curseforge_slug=
modrinth_id=
github_repo=
maven_url=https://maven.iglee.fr/releases
